Richb hanover patch 1
network-quality/draft-cpaasch-ippm-responsiveness pull request #7
Opened 2021-08-14 01:48 UTC by richb-hanover

Full editorial pass across the whole document. I'll also send a Word version with Track Changes on...

2021-08-16 22:18 UTC, cpaasch commented
Hi Rich! A bunch of unrelated files were added with this PR. Can you remove these? (going over your change in .md now)

2021-08-17 00:52 UTC, richb-hanover commented
I have found these tools (markdownlint and spellcheck) really useful for maintaining other large Markdown documents. They found about 20 misspellings and other problems in the document.

But I don't really understand the workflow for writing/maintaining an RFC for an I-D. Will they hinder the creation of the spec? Thanks.

2021-08-17 00:59 UTC, richb-hanover commented
Done. It's easy to add them back.

2021-08-18 21:27 UTC, cpaasch requested changes
First pass done! Looks good besides some of the comments I added.

2021-08-18 21:27 UTC, cpaasch commented on draft-cpaasch-ippm-responsiveness.md
> +The "bottleneck node" is one where the queueing occurs during heavy traffic.
I'm not sure about this phrase here. What does it add to the message just above where we try to conveye why bufferbloat is a subtle problem that on one side largely impacts user-experience while on the other side is so short-lived that it gets often just shrugged away.

2021-08-18 21:27 UTC, cpaasch commented on draft-cpaasch-ippm-responsiveness.md
> +network quality with the two "standard: measures: throughput and idle latency.
There must be a typo with ```"standard: measures: throughput```

2021-08-18 21:27 UTC, cpaasch commented on draft-cpaasch-ippm-responsiveness.md
> +The measurement methodology should explore/exploit all of these as they affect the user- experience.
Not sure about the "exploit" term here. Can you elaborate?

2021-08-18 21:27 UTC, cpaasch commented on draft-cpaasch-ippm-responsiveness.md
>  However, a number caveats come with measuring in parallel:
While you are at it, can you add an "of" between "number" and "caveats" ? ;-)

2021-08-18 21:27 UTC, cpaasch commented on draft-cpaasch-ippm-responsiveness.md
> +This is an open area for investigation. *(true?)*
Yes, this is true :) You can remove the ```*(true?)*``` :)

2021-08-18 21:36 UTC, cpaasch commented
One more comment: Feel free to add yourself in the Acknowledgements section :-) (otherwise, I will do it ;-) )

2021-08-19 01:10 UTC, richb-hanover commented
Thank you for all the comments. I will review them and roll them into a future update. (By Friday?)

2021-08-19 01:21 UTC, richb-hanover commented
PS Two scaffolding questions:

* How do you build kramdown? brew doesn't seem to do it, nor did I find a docker image. (I am using https://xml2rfc.tools.ietf.org/experimental.html to check the RFC, but it's awkward...)
* Those extra files I initially added into my patch make it easier to maintain a well-formatted Markdown document and to check the spelling. Are they not useful? 

Thanks again.

2021-08-19 15:41 UTC, cpaasch commented
Hello,

> PS Two scaffolding questions:
> 
> * How do you build kramdown? brew doesn't seem to do it, nor did I find a docker image. (I am using https://xml2rfc.tools.ietf.org/experimental.html to check the RFC, but it's awkward...)

Yes, that's the one you should use. When you have all the tools installed, you should be able to just type ```make```.

> * Those extra files I initially added into my patch make it easier to maintain a well-formatted Markdown document and to check the spelling. Are they not useful?

How can one use them? Which commands do you run? If it's useful, we can integrate that in the makefile.


Thanks,
Christoph

2021-09-06 13:45 UTC, richb-hanover commented
Hi Christoph - I updated the document with an eye toward it being cited by my note to the IAB Workshop next week. Thanks.

2021-09-07 22:59 UTC, cpaasch commented
@richb-hanover  - I'm going to merge this as is and do a pass over it to fix some of the comments I left. IAB camera-ready deadline is today, so we need to move quickly.

Nevertheless, we can still evolve the document beyond the IAB workshop as ultimately we want this to become a full IETF-standard.

2021-09-07 23:00 UTC, merged

2021-09-08 00:37 UTC, richb-hanover commented
> I'm going to merge this as is and do a pass over it to fix some of the comments I left. IAB camera-ready deadline is today, so we need to move quickly.
> 
> Nevertheless, we can still evolve the document beyond the IAB workshop as ultimately we want this to become a full IETF-standard.

Absolutely. Thanks!

2021-09-08 01:58 UTC, richb-hanover commented
PS I created a new PR that incorporates the PDF, HTML, text, PS, and XML versions so that a more readable form is available without running `make`